---
blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/ChapterHouse/route_interceptor/discussions
    about: Please ask and answer questions and propose new features.